Models/ErrorViewModel.cs
namespace PhotoViewer.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/Photo.cs
namespace PhotoViewer.Models
{
    public class Photo
    {
        public int ID { get; set; }
        public required string ThumbnailURL { get; set; }
        public DateTime Date { get; set; }
    }
}

Models/PhotosModel.cs
using PhotoViewer.Data;

namespace PhotoViewer.Models
{
	public class PhotosModel
	{
		public required List<Photo>	Photos {  get; set; }
		// Other properties.
	}
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PhotoViewer.Data;
using PhotoViewer.Models;
using System.Diagnostics;

namespace PhotoViewer.Controllers
{
	public class HomeController : Controller
	{
        private readonly ApplicationDbContext _context;
		private readonly ILogger<HomeController> _logger;

		public HomeController(ApplicationDbContext context, ILogger<HomeController> logger)
		{
            _context = context;
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View(new PhotosModel() { Photos = _context.Photos.ToList() });
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/PhotosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PhotoViewer.Data;

namespace PhotoViewer.Controllers
{
    public class PhotosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PhotosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Photos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Photos.ToListAsync());
        }

        // GET: Photos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos
                .FirstOrDefaultAsync(m => m.ID == id);
            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }

        // GET: Photos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Photos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ThumbnailURL,Date,Width,Height")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(photo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(photo);
        }

        // GET: Photos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos.FindAsync(id);
            if (photo == null)
            {
                return NotFound();
            }
            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ThumbnailURL,Date,Width,Height")] Photo photo)
        {
            if (id != photo.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(photo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhotoExists(photo.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(photo);
        }

        // GET: Photos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos
                .FirstOrDefaultAsync(m => m.ID == id);
            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var photo = await _context.Photos.FindAsync(id);
            if (photo != null)
            {
                _context.Photos.Remove(photo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhotoExists(int id)
        {
            return _context.Photos.Any(e => e.ID == id);
        }
    }
}

Views/Home/Index.cshtml
@using Newtonsoft.Json
@using PhotoViewer.Data
@model PhotosModel
@{
	ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4 page-title">Sander Broos Photography</h1>
</div>

<div class="d-flex justify-content-center gap-4">
	<button id="myButton2023" class="btn btn-info">2023</button>
	<button id="myButton2024" class="btn btn-info">2024</button>
</div>

<div id="myImageGrid" class="image-grid">
</div>

<div id="myImageItemTemplate" style="display: none">
	@*<div class="image-item"> *@
		<img/>
	@*</div> *@
</div>

<div id="fullSizeImageContainer">
	<img id="fullSizeImage" src="https://cdn.myportfolio.com/daed2eb3-8b71-4138-becb-64df2093a364/120780e1-f390-416c-acb2-a4be5c8428e6_rw_1920.jpg?h=7515e979348fcda03e9fdbfecec71278" />
</div>

@section Scripts {
	<script src="js/Gallery.js"></script>
	<script>
		var theGallery;
		$(document).ready(function () {
			theGallery = new Gallery(@Html.Raw(JsonConvert.SerializeObject(Model.Photos)));
		});
	</script>
}

Views/Photos/Create.cshtml
@using PhotoViewer.Data
@model Photo

@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <h1>Create</h1>

    <h4>Photo</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ThumbnailURL" class="control-label"></label>
                    <input asp-for="ThumbnailURL" class="form-control" />
                    <span asp-validation-for="ThumbnailURL" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Width" class="control-label"></label>
                    <input asp-for="Width" class="form-control" />
                    <span asp-validation-for="Width" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Height" class="control-label"></label>
                    <input asp-for="Height" class="form-control" />
                    <span asp-validation-for="Height" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Photos/Delete.cshtml
@using PhotoViewer.Data
@model Photo

@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Photo</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.ThumbnailURL)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.ThumbnailURL)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Date)
            </dd>
        </dl>
    
        <form asp-action="Delete">
            <input type="hidden" asp-for="ID" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

Views/Photos/Details.cshtml
@using PhotoViewer.Data
@model Photo

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <h1>Details</h1>

    <div>
        <h4>Photo</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.ThumbnailURL)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.ThumbnailURL)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Date)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
</div>

Views/Photos/Edit.cshtml
@using PhotoViewer.Data
@model Photo

@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <h1>Edit</h1>

    <h4>Photo</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ID" />
                <div class="form-group">
                    <label asp-for="ThumbnailURL" class="control-label"></label>
                    <input asp-for="ThumbnailURL" class="form-control" />
                    <span asp-validation-for="ThumbnailURL" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Width" class="control-label"></label>
                    <input asp-for="Width" class="form-control" />
                    <span asp-validation-for="Width" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Height" class="control-label"></label>
                    <input asp-for="Height" class="form-control" />
                    <span asp-validation-for="Height" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Photos/Index.cshtml
@using PhotoViewer.Data
@model IEnumerable<Photo>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <h1>Index</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Image
                </th>
                <th>
                    Dimensions
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <img src=@item.ThumbnailURL style="height: 150px;" />
                    </td>
                    <td>
                        @item.Width x @item.Height
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhotoViewer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PhotoViewer.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PhotoViewer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Photos" asp-action="Index">Photo Management</a>
                        </li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
					</ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PhotoViewer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>